version: '3'

services:
  identity.api:
    image: identity.api
    build:
      context: .
      dockerfile: src/Services/Identity.API/Dockerfile
  lbi.web:
    image: mjknowles/lazy-barre-instructor:20
    ports:
      - "32770:80"

